
name: '*_model'

config-version: 2
version: '1.0.0'

profile: '*'

require-dbt-version: ">=1.0.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Configuring models
models:
  *_model:
    staging:
      +materialized: table

    utils:

    domain:
      +materialized: table

    presentation:
      +materialized: table